### PR TITLE
Remove not needed library.

### PR DESCRIPTION
**Pull request by HellraiserTwo**

### CODE REVIEW

**Comment by HumanTree92** [comment]
I just want to clarify to make sure that this won't use up a Weapon Clip or Weapon Box if a player has a melee weapon out.

**Comment by HellraiserTwo** [comment]
I didn't think about that, let me fix that real quick, sorry.

**Comment by HellraiserTwo** [comment]
I checked and It is already secured on the client side.

**Comment by HumanTree92** [comment]
Added in https://github.com/HumanTree92/esx_extraitems/commit/bd806408a6b51894480aca78ec667b9830d099b6

**Pull request closed without merging**
